version: "3.7"
services:
  cluster-creator:
    image: potatohd/cluster-creator
    container_name: cluster-creator
    volumes:
      - ./.env:/app/.env
      - ./id_rsa.pub:/app/id_rsa.pub
      - ./cluster.tf:/app/cluster.tf